
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # joint Motor Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_lhip
    pid: {p: 600.0, i: 0.00, d: 0.0}
    #setpoint : 0
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: l_hip_r
    pid: {p: 600.0, i: 0.00, d: 0.0}
    #setpoint : 0
  joint3_position_controller:
    type: velocity_controllers/JointVelocityController
    #type: effort_controllers/JointVelocityController
    joint: l_shank_wheel
    #pid: {p: 0.2, i: 0.00, d: 0.0}
    #setpoint : 0

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_rhip
    pid: {p: 600.0, i: 0.00, d: 0.0}
    #setpoint : 0

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: r_hip_r
    pid: {p: 600.0, i: 0.00, d: 0.0} 
    #setpoint : 0
  joint6_position_controller:
    type: velocity_controllers/JointVelocityController
    #type: effort_controllers/JointVelocityController
    joint: r_shank_wheel
    #pid: {p: 0.2, i: 0.00, d: 0.0}
    #setpoint : 0
  